name: Bug Report
description: File a bug report
title: "[Bug] "
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        ❗ **Before opening a bug report**, please check whether the behaviour has already been reported in [existing issues](../../issues).

        Thank you for taking the time to report a bug. To help us address this as quickly as possible, please provide the information below.

  - type: dropdown
    id: architecture
    attributes:
      label: System Architecture
      description: Please select the architecture of your system.
      options:
        - ARM-64 (Apple Silicon)
        - Intel (x86_64)
        - Hackintosh (non-Apple hardware)
    validations:
      required: true

  - type: input
    id: os_version
    attributes:
      label: Operating System Version
      description: |
        Please specify your operating system version.

        *From the Apple menu  in the top-left corner of your screen, choose "About This Mac".*
      placeholder: e.g., macOS 14.2 Sonoma
    validations:
      required: true

  - type: input
    id: app_version
    attributes:
      label: Application Version
      description: |
        Please specify the version of the application.

        *From the Oliphaunt menu in the top-left corner of your screen, choose "About Oliphaunt".*
      placeholder: e.g., 1.0
    validations:
      required: true

  - type: input
    id: build_number
    attributes:
      label: Build Number
      description: |
        Please specify the build number. This is not the same as the application version — it appears in round brackets next to the version, e.g. Version 3.4 (31).

        *From the Oliphaunt menu in the top-left corner of your screen, choose "About Oliphaunt" and copy the number in brackets.*
      placeholder: e.g., 31
    validations:
      required: true

  - type: dropdown
    id: installation_source
    attributes:
      label: Installation Source
      description: Where did you install the application from?
      options:
        - App Store
        - TestFlight
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: Please provide a step-by-step guide to reproduce the behaviour.
      placeholder: |
        1. Launch the application.
        2. Click on "..."
        3. Scroll down to "..."
        4. Observe the issue.
    validations:
      required: true

  - type: textarea
    id: expected_behaviour
    attributes:
      label: Expected Behaviour
      description: What did you expect to happen?
      placeholder: The application should...
    validations:
      required: true

  - type: textarea
    id: actual_behaviour
    attributes:
      label: Actual Behaviour
      description: What actually happened?
      placeholder: Instead, the application...
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain the issue.
      placeholder: Paste or drag and drop screenshots here.

  - type: textarea
    id: screen_recordings
    attributes:
      label: Screen Recordings
      description: If applicable, add screen recordings to help demonstrate the issue.
      placeholder: Paste or drag and drop screen recordings here.

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context that might be helpful. You may upload a crash report, log file, or describe related symptoms.
